name: CI/CD PIPELINE

on:
  push:
    branches:
      main
  workflows_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Build docker image
        run: docker build -t spring-boot-image-app:latest .


